#!/bin/bash
#PBS -l walltime=8:00:00
#PBS -l select=1:ncpus=1:ngpus=1:mem=32GB
#PBS -q normal
#PBS -P 12004268
#PBS -N multimodal_survival_analysis
#PBS -j oe
#PBS -o /home/users/ntu/giabaoca/myProject-12004268/giabao/CLAM/log/extract_plip_features.txt

cd /home/users/ntu/giabaoca/myProject-12004268/giabao/CLAM #need to change directory to the project folder first

#activating conda environment
source activate base
conda activate clam_latest

#check
conda info --envs

# create patches
# python ./lib/patch_extractor.py --source wsi_files/BLCA --save_dir wsi_patches/BLCA  --target_magnification 2.5 --patch --seg --stitch

#run the file
python ./lib/feature_extractor.py --h5_dir wsi_patches/BLCA/patches --wsi_dir wsi_files/BLCA --output_dir wsi_patches/BLCA/features/BLCA_plip --patch_level 1 --target_patch_size 224 --feature_extractor plip

