#!/bin/bash
#PBS -l walltime=10:00:00
#PBS -l select=1:ngpus=1:mem=32GB
#PBS -q normal
#PBS -P 12004268
#PBS -N multimodal_survival_analysis
#PBS -j oe
#PBS -o /home/users/ntu/giabaoca/myProject-12004268/giabao/CLAM/log/train_with_resnet.txt

cd /home/users/ntu/giabaoca/myProject-12004268/giabao/CLAM #need to change directory to the project folder first

#activating conda environment
source activate base
conda activate clam_latest

#check
conda info --envs

python run.py --batch_size 16 --hidden_dim 128 --feature_dir wsi_patches/BLCA/features/BLCA_plip --h5_dir wsi_patches/BLCA/patches/ --clean_csv_path dataset_csv/tcga_blca_all_clean.csv --encoder plip --log_path experiments/result_plip.jsonl
